[package]
name = "tokio_test_client"
version = "0.1.0"
edition = "2021"

[dependencies]
jwt = "0.16.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
tokio-macros = "2.3.0"
